### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ghost** [meesam4687/auto-reply-dms-discord#1]
i have a problem 

it says AFK Thingy Ready. so that good
but it does not send the afk mesage

**Comment by meesam4687** [comment]
hmm weird
can you try closing all the dms and try again?

**Comment by ghost** [comment]
it works now but can you add that i dont need to enter the message every time

**Comment by meesam4687** [comment]
> it works now but can you add that i dont need to enter the message every time

Sure I will do that if I get some free time

**Comment by ghost** [comment]
okey
